"""empty message

Revision ID: 2aa1c0b8f550
Revises: 6345f1239266
Create Date: 2023-09-15 02:49:23.238351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa1c0b8f550'
down_revision = '6345f1239266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table_orders',
    sa.Column('products', sa.Integer(), nullable=True),
    sa.Column('ordenes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordenes'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['products'], ['products.id'], )
    )
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'driver', ['delivery_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=4, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('delivery_id')

    op.drop_table('association_table_orders')
    # ### end Alembic commands ###
