"""empty message

Revision ID: 379b91678ba2
Revises: 2aa1c0b8f550
Create Date: 2023-09-15 16:58:36.215554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379b91678ba2'
down_revision = '2aa1c0b8f550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=4, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
