"""empty message

Revision ID: 68911bd5e674
Revises: 452bcedfe65e
Create Date: 2023-09-14 01:32:40.572342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68911bd5e674'
down_revision = '452bcedfe65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('vehicle', sa.Enum('MOTO', 'CARRO', name='vehicletype'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver')
    # ### end Alembic commands ###
